# Generated by Django 3.2.8 on 2021-10-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('W', 'Player won match against bot'), ('L', 'Player lost match against bot'), ('T', 'Player tied match with bot'), ('U', 'Match undecided / unfinished')], default='U', max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('player_selection', models.CharField(choices=[('X', 'No selection'), ('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], default='X', max_length=1, null=True)),
                ('bot_selection', models.CharField(choices=[('X', 'No selection'), ('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], default='X', max_length=1, null=True)),
                ('outcome', models.CharField(choices=[('W', 'Player won round against bot'), ('L', 'Player lost round against bot'), ('T', 'Player tied round with bot')], default='T', max_length=1, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds_played', to='janken.match')),
                ('round_number', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_played', to='janken.player'),
        ),
    ]
